# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "map_restfully"
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["CLR"]
  s.date = "2011-10-19"
  s.description = "Convenience method to provide controller actions that correspond to the HTTP verbs."
  s.email = "clr@port49.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/map_restfully.rb",
    "test/helper.rb",
    "test/test_rack.rb",
    "test/test_routes.rb"
  ]
  s.homepage = "http://github.com/clr/map_restfully"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Provide HTTP-verb style routing to Rails."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 3.0.10"])
      s.add_runtime_dependency(%q<rack-test>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_runtime_dependency(%q<rails>, ["~> 3.0.10"])
      s.add_runtime_dependency(%q<rack-test>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["~> 3.0.10"])
      s.add_dependency(%q<rack-test>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rails>, ["~> 3.0.10"])
      s.add_dependency(%q<rack-test>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 3.0.10"])
    s.add_dependency(%q<rack-test>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rails>, ["~> 3.0.10"])
    s.add_dependency(%q<rack-test>, [">= 0"])
  end
end

